name: Deployment
on:
  push:
    branches: [ main ]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.20.1
          cache: npm
      - run: npm i
      - run: npm run test  
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          service-id: srv-cf0klvsgqg45vetaj58g
          retries: 20
          wait: 16000
          sleep: 30000
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: deploy
    env:
      CYPRESS_BASE_URL: https://calculator-2581.onrender.com
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.20.1
          cache: npm
      - run: npm i
      - run: npm run e2e
  